### ISSUE TITLE
WebCore VideoFullscreenControllerContext::currentTimeChanged(double, double) crash

### ISSUE THREAD

**Issue by fdobre** [3qnexx/nexxPLAY-iOS#1]
IOS 12, version 5.9.69
WebCore
VideoFullscreenControllerContext::currentTimeChanged(double, double)
![screen shot 2018-08-24 at 12 16 21 pm](https://user-images.githubusercontent.com/3833179/46276084-54cbaf80-c55f-11e8-8eb6-cf2ee8e18f9e.png)

**Comment by fdobre** [comment]
Since IOS 12 was released we started to have a lot of crashes caused by this error. Please let us know if there is anything to to on our side to fix it.

**Comment by boredom2** [comment]
This looks like an android Stack for me?
