### ISSUE TITLE
Archiving Bitcode Errors

### ISSUE THREAD

**Issue by Heidi0039** [3qnexx/nexxPLAY-iOS#10]
I'm able to build and launch my app in the simulator and my connected device but when archiving my app using Xcode 11.4, I get Bitcode errors.

**Logs**
ld: bitcode bundle could not be generated because 'PATH/nexxPLAY-iOS/version 6.0.1/nexxPlay.framework/nexxPlay' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file 'PATH/nexxPLAY-iOS/version 6.0.1/nexxPlay.framework/nexxPlay' for architecture arm64

**Test environment Info:**

Device: [e.g. iPhone11]
OS: [e.g. iOS13]
Version: nexxPLAY-IOS: [e.g. 6.0.1]

**Additional context**
I'm also not able to archive the actual SDK in this repository.

**I think maybe the fix is:**
Rebuild nexxPLAY-IOS distributions with bitcode enabled

**Comment by DanielLeberle** [comment]
When exactely do you get the error? While archiving or while trying to upload the archive to appstore connect?

**Comment by Heidi0039** [comment]
While archiving.

**Comment by DanielLeberle** [comment]
I could reproduce the issue and fixed it in release 6.0.2, please try the new version and let me know if it works. Thanks!

**Comment by Heidi0039** [comment]
This fixed my issue. Thanks!
I can now archive as expected.
