### ISSUE TITLE
onAudioPlayerProgressChanged notification does not fire when the playback is triggered on lockscreen 

### ISSUE THREAD

**Issue by andreaspetsch** [3qnexx/nexxPLAY-iOS#12]
**How to reproduce** 
1.) Start playback in the app
2.) Pause playback in the app
3.) Start the playback on the lock screen 
4.) Switch back to the app

=> onAudioPlayerProgressChanged notification does not fire

**environment**
iPhone XS
iOS 13.5
nexxPlay SDK v6.0.4

**Comment by DanielLeberle** [comment]
On iOS all notifications have the prefix "NexxPlay" e.g. the notification when the player is paused is named "NexxPlayPauseNotification". So there is no notification called "onAudioPlayerProgressChanged" that is sent by the iOS SDK.
I just tried to recreate the false behaviour but my demo app seems to report all notifications for play/pause correctly, regardless of where the media is controlled.
