### ISSUE TITLE
Compiling with Swift 5.3 for xcode 12.0

### ISSUE THREAD

**Issue by Heidi0039** [3qnexx/nexxPLAY-iOS#14]
Since Wednesday, when iOS 14 was launched I am unable to compile any App which includes NexxTV.

<img width="465" alt="Bildschirmfoto 2020-09-21 um 10 21 28" src="https://user-images.githubusercontent.com/8172336/93745812-6dbe4700-fbf4-11ea-95ea-c076cf04ceef.png">

**Comment by boredom2** [comment]
We will provice a new SDK Version with new Features, optimized for iOS14 early next Week.
Nevertheless, for your convenience, we will release an iOS14-compatible Version today, so you can continue working.

**Comment by boredom2** [comment]
Sadly, there is an Issue with Google IMA, that does not compile on iOS14, thats we cannot release an Update. We will keep you updated.

**Comment by DanielLeberle** [comment]
Hi, I just added a new version, please try and let me know if everything is ok!

**Comment by Heidi0039** [comment]
6.0.12 is still the latest version available.

**Comment by DanielLeberle** [comment]
Sorry there was an error during the upload to git. It should be available now! But you can find it under releases too!

**Comment by Heidi0039** [comment]
Version 6.0.13 is working with Swift 5.3 as expected.

I am getting the following error in certain scenarios:

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<nexxPlay.AdWebView 0x1432d7750> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key wv_ad.'

Is this a mistake in my implementation or can you provide me with a fix?

**Comment by DanielLeberle** [comment]
Hi, the error seems to occur when the user taps on an ad and is presented the corresponding website. Can you reproduce the error with the latest version?

**Comment by Heidi0039** [comment]
Using the latest version I am getting the following error:

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<nexxPlay.InternalPlayerView 0x14da7beb0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key btn_start.'

This happens before the old error was triggered. Therefor I am unsure wether the old error is fixed, as it might occur after getting past this new error.

**Comment by DanielLeberle** [comment]
Hi,

how did you update the SDK? Did you remove the old and add the new one or did you replace it? 
This error does not seem to refer to the latest code since InternalPlayerView does not have the attribute btn_start anymore.

Could you please remove the SDK and add it again, then make a clean build and try again?

And I assume you are developing with Obj-C?

**Comment by Heidi0039** [comment]
I am developing in Swift/SwiftUI using xCode12.

A clean replacement of the new Framework seems to prevent this error. I am now using v6.3.0
However when calling NexxPLAYView.startPlay(streamType:mediaID:configuration) my app Terminates without warning and without any meaningful Stacktrace or helpful information...

My implementation is unchanged an was working as expected with previous Framework Versions.

**Comment by DanielLeberle** [comment]
can you provide me with the data you pass to the player? environment, config, stream type and media id? then I try to reproduce the error

**Comment by Heidi0039** [comment]
I use the following data:

Environment(domain: "12113")
View(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.width / 16 * 9))
startPlay(streamType: "video", mediaID: "1710447", configration: Config())

The same behaviour occurs with different mediaIDs

**Comment by boredom2** [comment]
Hi there, 

although off-topic, I would like to add, that you should add the "consentString" Property on the Environment - if you have it.
As at least on your WebSites, you use a TCF Framework, the given User Consent String should (and must) be provided to all Advertisers. Therefore, we strongly recommend to pass that String to the Player.

Thanks!
Christoph

**Comment by DanielLeberle** [comment]
I just released a new version that should fix the issue. Please update and let me know if there are any other problems!

**Comment by Heidi0039** [comment]
With xCode 12.2 released and developing for iOS 14.2 I can no longer build with the following error (similar to the intial Issue in this Ticket).

![Bildschirmfoto 2020-11-16 um 13 07 09](https://user-images.githubusercontent.com/8172336/99250894-bcf7b100-280c-11eb-980d-9660296ba156.png)

**Comment by DanielLeberle** [comment]
I just released v6.3.2 that was built with the new Xcode version. Please update and let me know if there are any other problems!

**Comment by Heidi0039** [comment]
I am still getting the exact same error when using v6.3.2

**Comment by DanielLeberle** [comment]
I just tried to recreate the issue with a new Xcode 12.2 project but everything works fine.

Did you remove the old version of nexxplay, add the new one and make a clean build?

**Comment by Heidi0039** [comment]
I did exactly that, any other ideas?

**Comment by DanielLeberle** [comment]
maybe deleting the derived data helps. Otherwise you could also try and create a new blank project with the latest nexxPLAY SDK and see if the error occurs there as well. If yes, please send me the blank project!

**Comment by Heidi0039** [comment]
I can successfully build my Project using any Simulator (ios 14.2), however a real device (ios 14.2) is unsuccessful, does that provide any help?

I am using xCode Version 12B45b

EDIT:
I was not using the Framework in a Debug Environment, therefor the build was successful. When using the NexxPLAY Framework 6.3.2 I can't build on either target device.

**Comment by DanielLeberle** [comment]
So when you try to build your project on a real device, you get the compiler error from above?

**Comment by Heidi0039** [comment]
Thats correct

**Comment by DanielLeberle** [comment]
So with 6.3.2 you get the error for both targets, simulator and device?

**Comment by Heidi0039** [comment]
Yes

**Comment by Heidi0039** [comment]
I have now tried using the 6.3.2 in a new example Project with success.
I will see into the differences compared to my ongoing Project. It might be connected to an older GoogleIMA version?

**Comment by DanielLeberle** [comment]
As you correctly said the problem only occurs when the target simulator/device is on iOS 14.2. I have a test project that does not work when I select iOS14.2. simulators

**Comment by DanielLeberle** [comment]
I released a new version that should better work with Xcode 12.2

One thing that you have to do in your build settings: 
under "Excluded Architectures" add "arm64" for "Any iOS Simulator SDK"

**Comment by Heidi0039** [comment]
Compiling now works for the current Xcode Version
