### ISSUE TITLE
v6.3.2: AVAudioSession Category unsupported combination

### ISSUE THREAD

**Issue by Heidi0039** [3qnexx/nexxPLAY-iOS#16]
After now successfully using the new FrameworkVersion I get the following runtimeError:

`AVAudioSession_iOS.mm:341   AVAudioSessionCategorySoloAmbient category is not supported in combination with AVAudioSessionRouteSharingPolicyLongFormAudio`

This error occurs when popping my current page while a video is playing (going back with a swipe animation or pressing the "back" button of my NavigationView)

Edit: This seems to only happen if an Ad is playing at the time of going back. If a Video is playing it is working as intended.
Edit2: I can pin this issue on a **specific** Ad. (Some work, others don't) Is it possible that an ad is requesting specific AudioSessionCategories based on its content?

**Comment by DanielLeberle** [comment]
are you using Google IMA to show ads?

**Comment by Heidi0039** [comment]
Yes.
Currently with v3.13.0. Which is the newest Version to my knowledge.

**Comment by DanielLeberle** [comment]
I checked the nexxPLAY code, we never use `AVAudioSessionCategorySoloAmbient` and as you described this seems to be a problem within the Google IMA SDK unfortunately.

**Comment by Heidi0039** [comment]
After further looking into the Problem it seems like the AVAudioSession is just a warning and not leading to the apps termination.
What leads to it is actually the following: `*** -[nexxPlay.NexxPlayer retain]: message sent to deallocated instance`

After popping my current View the Player is deallocated but still being accessed from somewhere.

In my Players lifetime I add notificationObservers for Fullscreen and Error handling, however in its deinit I make sure to remove these observers `self.notificationCenter.removeObserver(self)`. This is also called as expected before the app terminates (and before the error occurs).

Am I responsible for cleaning up/deallocating other parts of the player that I am not aware of?

**Comment by Heidi0039** [comment]
FYI: The same behaviour occurs using v6.3.3

**Comment by DanielLeberle** [comment]
Does the app always crash when you close the view with the player?
Can you maybe provide a call stack?

**Comment by Heidi0039** [comment]
It always happens if Ads are playing when going back. 
If the video is playing instead (or nothing at all), everything works as expected.

**Comment by DanielLeberle** [comment]
I tried to reproduce the problem in my demo app, but everything seems to be deallocated correctly. I can see that all deinit methods are called and nothing crashes.
Do you maybe have weak references on the player that are not unwrapped safely?

**Comment by Heidi0039** [comment]
I could recreate this issue in an example Project.
In this example Project the same crash occurs, however it is triggered slightly differently.

I have stripped everything down to the bare minimum and hope it is understandable.
I hope you can set this up and it won't be to much trouble changing all Signature/Permission/UserPaths and whatever else there might be.

You can find the exampleproject here: https://next.vonaffenfels.de/s/9GCaYtQpagtaCKy

Everything relevant, including Steps to reproduce, should be inside the ContentView.swift.

**Comment by DanielLeberle** [comment]
thanks for the demo project! I can reproduce the error.

I'm not sure if its because of SwiftUI but whether its the video or the ad, whenever you press Back, the video/ad still plays so the nexxPLAY View has not been deallocated correctly. I Do not have that issue with my UIKit implementation so maybe its because of SwiftUI?

Another thing: when the ad is paused and you go back, then start the video again and there is no error. So it seems to be something inside the IMA sdk, but not sure yet

**Comment by DanielLeberle** [comment]
I just created a project where I use only UIKit and there everything works fine. I push a view controller with the player view. While the ad is playing, I push the Back button to navigate back. Then the ad is stopped automatically and I can also push the view controller again.

**Comment by Heidi0039** [comment]
So this essentially means that a SwiftUI implementation is currently not supported?

**Comment by DanielLeberle** [comment]
I extended your demo project by implementing the `viewWillDisappear` method of `NexxController` like this:

```
 override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        for view in view.subviews {
            view.removeFromSuperview()
        }
    }
```

This code removes all subviews of the view controllers view. If you only want to remove the player view you can do this as well of course.          
With this code pushing and popping the view multiple times works as expected and also the player stops once the view controller is popped.

**Comment by Heidi0039** [comment]
I have found a similar solution just before you have provided yours.
When storing the NexxPLAYView in a variable and removing it from its Superview on viewWillDissapear.

I am still unsure of what is happening internaly. Why is this only leading to errors when Ads are playing?
I feel like I shouldn't be necessary to remove all subviews on Disappear. I'm pretty sure there are usecases where keeping them is desired.

However this workaround can be used in my project so I'm good.

**Comment by Heidi0039** [comment]
Upon implementing and further testing I noticed that unfortunately this workaround does not seem to work.

I had a few Problems.
The first one is that on a BackSwipe Gesture the Player gets deallocated even when aborting the gesture and returning to the current Page.
This however, can be solved by using viewDidDisappear instead of viewWillDisappear.

Another Problem occured when keeping references to the player from SwiftUI, for example to implement Play/Pause Buttons within my Page, or for whatever other reason, and then using this PlayerReference to call functionality of the Player.

When using these Functions everything was working as Intended, namely Pausing/Starting/Resuming the Video.
However using continuous checkups on the Player like isPlaying or others like so:
```
private var isPlaying: Bool {
  get {
    if(self.player == nil) {
      return false
    }
    return self.player!.isPlaying
  }
}
```
was causing issues down the road. It seems like the `self.player == nil` check was not returning correctly.
After making sure that I am not holding unnecessary references myself and deallocating everything properly I could still find this issue.
I feel like the AD (IMA) is keeping the player from fully deallocating, and therefor my check is resulting in false. However when then calling functionality of this player (`self.player!.doSomething()`) the application crashed.

Upon trying to solve this problem further I found a workaround which seems to work.

Instead of keeping references to the Player to access its functionality I am now passing in a PasstroughSubject (import Combine) on its constructor.
Instead of calling functionality of my player reference I am now Sending the Signal trough my PasstroughSubject which is connected by an AnyCancellable Handler.

So my old code (example Pause function):
```
// Somewhere in SwiftUI
self.pause()
//

// Functionality
private func pause() {
   if(self.isPlaying) {
    self.player!.pause()
  }
}
```


turned into

```
private let playerAction = PasstroughSubject<PlayerAction, Never>()

// Somewhere in SwiftUI
self.playerAction.send(.Pause)
//

// UIViewController handels the signal using AnyCancellable
private var playerActionHandling: AnyCancellable!
self.playerActionHandling = self.playerAction.sink { action in
    switch(action) {
        case .Pause: self.player.pause()
          break
         // More cases
    }
}
```
Hopefully this can help someone else who has the same Problem.
Maybe this can also lead to a fix in the future, as keeping the Reference to the Player should not cause these issues to begin with.

**Comment by Heidi0039** [comment]
The `ViewDidDisappear` and `ViewWillDisappear` functions are called when the device is rotated in Fullscreen mode, which leads to all kinds of followup problems.

Adding Observers for Fullscreen enter/exit I can set a bool and check for Fullscreen before executing the `viewDidDisappear` logic.

```
self.notificationCenter.addObserver(self, selector: #selector(didEnterFullscreen(notification:)), name: NSNotification.Name(rawValue: NexxPLAYNotifications.EnterFullscreen), object: self.player)
self.notificationCenter.addObserver(self, selector: #selector(didExitFullscreen(notification:)), name: NSNotification.Name(rawValue: NexxPLAYNotifications.ExitFullscreen), object: self.player)


    @objc func didEnterFullscreen(notification: NSNotification) {
        self.isFullscreen = true
    }
    @objc func didExitFullscreen(notification: NSNotification) {
        self.isFullscreen = false
    }


    override func viewDidDisappear(_ animated: Bool) {
        if(self.isFullscreen) {
            return
        }
        super.viewDidDisappear(animated)
        self.notificationCenter.removeObserver(self)
        view.subviews.forEach({ $0.removeFromSuperview() })
   }
```

**Comment by DanielLeberle** [comment]
But you still have issues now? Or does the code provided by you solve the problem?

Do you start the player fullscreen or is fullscreen set by the button in the player UI?

**Comment by Heidi0039** [comment]
The code provided works around the problem. Hopefully there are no edgecases that I am unaware of.
Fullscreen is set by the player UI button.
