### ISSUE TITLE
Prevent Ads

### ISSUE THREAD

**Issue by Heidi0039** [3qnexx/nexxPLAY-iOS#17]
Hi,

I have a pretty straight forward question. Sorry for opening a new issue for this, but I am not sure how else I would contact you.

Is it possible to prevent ads from playing?
Say I have a "Pay 1€ and dont see ads in the App" purchase. 
I then can actively hide my Banner and Interstitial integration by simply not initializing/using it.

Is there something I can pass to the Player, Environment or Config to force it to play without ads?

Best regards,
Chris

**Comment by boredom2** [comment]
Hi there,

yes, sure.
In dynamic Cases like that, you can add an Override to the Configuration Object:
"disableAds":1

For Comparison:
https://play.docs.nexx.cloud/integration-enhancements/override-options#ad-management

Or here directly:
https://github.com/3qnexx/nexxPLAY-iOS#configuration
