### ISSUE TITLE
IPhone 13 and 14 wenn entering Fullscreen aspectratio bug

### ISSUE THREAD

**Issue by ghost** [3qnexx/nexxPLAY-iOS#19]
In version 6.4.3 - 6.4.6 if you play the Video in Fullscreen and enter landscape mode 
the aspectratio shifts to make the Video play outside of the screen.

**Comment by boredom2** [comment]
Hi there and thanks for the Hint. Do you have any sample Ids we can use for checking this?

**Comment by ghost** [comment]
videoId: 1828482

do you want the whole Data Structure?

**Comment by boredom2** [comment]
We will look into it, thanks.

**Comment by DanielLeberle** [comment]
Hi, 

I tried to reproduce the mentioned error, without success so far. 
Did you enter the fullscreen via the fullscreen button of the player or did you start the player already being in fullscreen mode?

**Comment by ghost** [comment]
I first play the video then click the fullscreen button and then tillt the phone to go into landscape mode

**Comment by DanielLeberle** [comment]
could you maybe provide a video of the bug?

**Comment by ghost** [comment]
https://github.com/3qnexx/nexxPLAY-iOS/assets/131875880/c4c69443-9f10-4fe9-8760-0239fc690baa

**Comment by DanielLeberle** [comment]
Hmm ok I have a couple more questions:
- is the app that is integrating the player a native app?
- if so, is it build with swiftUI or UIKit?
- is the player integrated in different views in your app and is the behaviour always the same?

**Comment by ghost** [comment]
It's a native app in UIKit it is integrated in different views and the behavior is the same in all of them

**Comment by DanielLeberle** [comment]
hmm ok are you modifying the UIWindow somehow? when the player goes "fullscreen" we add it to the window since we do not know the view hierarchy outside the player. This used to work pretty well and also in my test applications I can not reproduce the error.
