### ISSUE TITLE
WebCore VideoFullscreenControllerContext::rateChanged(bool, float) crash

### ISSUE THREAD

**Issue by fdobre** [3qnexx/nexxPLAY-iOS#3]
IOS 12, version 5.9.69

<img width="849" alt="screen shot 2018-10-01 at 9 58 29 am" src="https://user-images.githubusercontent.com/3833179/46276529-a7f23200-c560-11e8-883d-8b09aae26066.png">

**Comment by DanielLeberle** [comment]
Hi Florin,

all three issues are caused by iOS, I'm afraid we can not do anything about them

**Comment by fdobre** [comment]
We can close this as it seems not to be related to nexx player.
