### ISSUE TITLE
GoogleInteractiveMediaAds.framework not found

### ISSUE THREAD

**Issue by apm-thomas-meyer** [3qnexx/nexxPLAY-iOS#4]
We have problems to get the current Version 5.9.75 running with Xcode 10.

To demonstrate the problem, I created a test project and followed the provided instructions and got this error:

<img width="1355" alt="screenshot 2018-10-10 at 09 40 22" src="https://user-images.githubusercontent.com/38885491/46720710-951ee200-cc71-11e8-8f16-28691aa39335.png">

In another project in which we already successfully added the NexxSDK (5.9.62) we had to add the GoogleIMA framework in order to get the app starting. So to update the SDK from 5.9.62 to 5.9.75 in that app, I removed all the old files and added the new frameworks and the bundle just like before, except I also added the DailyMe framework. Unfortunately, I get the same error as above in the screenshot.

Let me know if there is anything you need from me to fix this.

Greetings

**Comment by fdobre** [comment]
I was able to solve GoogleInteractiveMediaAds  issues and build using pods:
 ` pod 'GoogleAds-IMA-iOS-SDK', '~> 3.7.2'`

I had similar problems with DailyMeSDK, for that I had to use similar steps as the nexx framework to integrate it in xCode 10.

**Comment by DanielLeberle** [comment]
Google IMA SDK and DailyMe SDK must be integrated to your project in order to use nexxPLAY.
You can download the version we support from our repository or add it via cocoapods (only Google IMA)

**Comment by apm-thomas-meyer** [comment]
Thanks guys, adding the GoogleIMA pod fixed it for me.
