### ISSUE TITLE
[5.9.77] Player freezes after NexxPlayProgress100Notification is triggered.

### ISSUE THREAD

**Issue by fdobre** [3qnexx/nexxPLAY-iOS#7]
![screen shot 2018-11-16 at 3 49 55 pm](https://user-images.githubusercontent.com/3833179/48625247-5d653180-e9b7-11e8-8b94-20e6f8390b1d.png)

**Comment by fdobre** [comment]
This issue was not present in 5.9.75

Reproduced in top 3 videos in Top Articles and possible in other videos.

This is a blocker for our release, please let us know if we can help you with more info or if there is anything to do on our side to remove this crash.

We are using getMediaData function for all our video analytics. If there are any breaking changes in that function please add them to release notes.

**Comment by fdobre** [comment]
We also noticed that for [5.9.77, 5.9.75] getMediaDataWithGetEnhanced crashes the player when called at NexxPlayPlayPosNotification event. We were able to avoid the crash by ignoring that event.

**Comment by fdobre** [comment]
Additional notes: 
Reproduced in several simulators (ios 12) and on  iPhone 8 (ios 12)

Steps: start player in partial or full screen, jump towards the end (maybe 95%) of the video, wait for the video to end.

**Comment by DanielLeberle** [comment]
thanks for the reports, I will have a look!

**Comment by DanielLeberle** [comment]
I just uploaded v5.9.78 please let me know if the issues still occur!

**Comment by fdobre** [comment]
Issue cannot be reproduced anymore in 5.9.78
