### ISSUE TITLE
Some videos that play in android have 'Video not found error' in IOS

### ISSUE THREAD

**Issue by fdobre** [3qnexx/nexxPLAY-iOS#8]
Version 5.9.78

title `Läuten bald die Hochzeitsglocken? Das sagen sie dazu`

id  425966

**Comment by fdobre** [comment]
@boredom2 @DanielLeberle any update on this? Can we help you with more info?

**Comment by DanielLeberle** [comment]
We could locate the issue, I will talk to @boredom2 and we will let you know once we have a solution!

**Comment by fdobre** [comment]
@DanielLeberle is it safe to release 5.9.78 now? Do you have any idea how many videos are affected by this and if this issue is present in 5.9.75 (current version in our production) too?

**Comment by fdobre** [comment]
Our QA team ran some tests today on several videos and they were not able to reproduce it anymore.
They are still testing 5.9.78, from our side this looks stable enough.

**Comment by boredom2** [comment]
This Issue is related to "static Datamode" - it only occured on Videos, that havent been updates a couple of Weeks or more. So - the older the Video, the higher the Chance to see this Issue (but we will fix it in the SDK anyway).

**Comment by fdobre** [comment]
@boredom2 Is the issue fixed in 5.9.79?

**Comment by boredom2** [comment]
Always ask @DanielLeberle , he knows far more than  I do here :)

**Comment by DanielLeberle** [comment]
@fdobre are there still videos that do not run on ios but on android?

**Comment by fdobre** [comment]
> @fdobre are there still videos that do not run on ios but on android?

@NetNetPumi2 should answer
